version: "3.8"

services:
  mongo:
    image: mongo:7.0
    container_name: sniffle-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: sniffle
      MONGO_INITDB_ROOT_USERNAME: sniffleuser
      MONGO_INITDB_ROOT_PASSWORD: snifflepass
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
